# Generated by scripts/generate-azure-dialect.ts.
concept "compute-placement" {
  description = "Availability, proximity, reservation, or host placement supporting Azure compute."
}

concept "disk-snapshot" {
  description = "A point-in-time snapshot of Azure disk storage."
}
