# Generated by scripts/generate-azure-dialect.ts.
concept "local-network-gateway" {
  description = "An Azure representation of an external VPN site gateway."
}

concept "network-policy-detail" {
  description = "A route, security rule, association, or network policy supporting Azure networking."
}

concept "private-link-scope" {
  description = "An Azure private-link scope or hub grouping private service connectivity."
}

concept "public-address" {
  description = "A public Azure IP address exposed to network traffic."
}
