# Generated by scripts/generate-aws-dialect.ts.
concept "container-repository" {
  description = "An Amazon ECR repository storing container images."
}

concept "repository-configuration" {
  description = "Configuration contributing to an AWS artifact repository."
}
