# Generated by scripts/generate-aws-dialect.ts.
concept "ecs-cluster" {
  description = "An Amazon ECS cluster providing container scheduling capacity."
}


concept "ecs-service" {
  description = "An Amazon ECS service maintaining a container workload."
}
