# Generated by scripts/generate-azure-dialect.ts.
concept "defender-plan" {
  description = "A Microsoft Defender for Cloud protection plan or workspace integration."
}

concept "managed-hsm" {
  description = "An Azure Key Vault Managed HSM security boundary."
}

concept "security-detail" {
  description = "A certificate, access policy, alert, connector, or security configuration."
}
