# Generated by scripts/generate-azure-dialect.ts.

rule "sentinel-automation-rule" {
  match {
    type = "azurerm_sentinel_automation_rule"
  }

  as = concept.security-detail
}

rule "sentinel-aws-cloudtrail-connector" {
  match {
    type = "azurerm_sentinel_data_connector_aws_cloud_trail"
  }

  as = concept.security-detail
}

rule "sentinel-entra-connector" {
  match {
    type = "azurerm_sentinel_data_connector_azure_active_directory"
  }

  as = concept.security-detail
}

rule "sentinel-nrt-alert-rule" {
  match {
    type = "azurerm_sentinel_alert_rule_nrt"
  }

  as = concept.security-detail
}


rule "sentinel-scheduled-alert-rule" {
  match {
    type = "azurerm_sentinel_alert_rule_scheduled"
  }

  as = concept.security-detail
}
