# Generated by scripts/generate-aws-dialect.ts.






concept "internet-gateway" {
  description = "Amazon VPC internet gateway as a durable AWS architecture entity."
}

concept "network-acl" {
  description = "Amazon VPC network ACL as a durable AWS architecture entity."
}

concept "route-table" {
  description = "Amazon VPC route table as a durable AWS architecture entity."
}

concept "security-group" {
  description = "Amazon VPC security group as a durable AWS architecture entity."
}

concept "transit-gateway" {
  description = "An AWS Transit Gateway connecting multiple networks."
}

concept "transit-gateway-attachment" {
  description = "A network attachment contributing to an AWS Transit Gateway."
}
