# Generated by scripts/generate-aws-dialect.ts.
rule "dsql-cluster" {
  match {
    type = "aws_dsql_cluster"
  }

  as = rf.concept.managed-database

  identity {
    attributes = ["arn", "identifier"]
    scope      = "provider"
  }

  endpoint {
    attributes = ["arn", "identifier"]
  }
}
