# Generated by scripts/generate-aws-dialect.ts.
concept "dynamodb-component" {
  description = "An index contributing to an Amazon DynamoDB table."
}


concept "dynamodb-table" {
  description = "An Amazon DynamoDB table, distinct from a managed database service instance."
}


rule "dynamodb-table" {
  match {
    type = "aws_dynamodb_table"
  }

  as = concept.dynamodb-table
}
