# Generated by scripts/generate-aws-dialect.ts.

rule "elasticache-cluster" {
  match {
    type = "aws_elasticache_cluster"
  }

  as = concept.managed-cache
}


rule "elasticache-replication-group" {
  match {
    type = "aws_elasticache_replication_group"
  }

  as = concept.managed-cache
}
