# Generated by scripts/generate-aws-dialect.ts.


rule "neptune-cluster" {
  match {
    type = "aws_neptune_cluster"
  }

  as = rf.concept.managed-database

  identity {
    attributes = ["arn", "cluster_identifier"]
    scope      = "provider"
  }

  endpoint {
    attributes = ["arn", "id", "cluster_identifier"]
  }
}
