# Generated by scripts/generate-aws-dialect.ts.
concept "db-proxy" {
  description = "Amazon RDS DB proxy as a durable AWS architecture entity."
}

concept "db-proxy-component" {
  description = "An endpoint or target group contributing to an Amazon RDS Proxy."
}


rule "db-proxy" {
  match {
    type = "aws_db_proxy"
  }

  as = concept.db-proxy
}
