# Generated by scripts/generate-azure-dialect.ts.
rule "role-assignment" {
  match {
    type = "azurerm_role_assignment"
  }

  as = concept.governance-detail
}

rule "role-definition" {
  match {
    type = "azurerm_role_definition"
  }

  as = concept.governance-detail
}
