# Generated by scripts/generate-azure-dialect.ts.
concept "operations-detail" {
  description = "An alert, diagnostic, workbook, schedule, dashboard, or operational configuration."
}

concept "third-party-monitor" {
  description = "A third-party observability service managed through Azure."
}
