# Generated by scripts/generate-azure-dialect.ts.
concept "api-management-detail" {
  description = "An API, product, backend, policy, workspace, or gateway configuration inside API Management."
}

concept "integration-connection" {
  description = "An Azure API or App Service connection supporting integration."
}
