# Generated by scripts/generate-aws-dialect.ts.


rule "fsx-lustre-file-system" {
  match {
    type = "aws_fsx_lustre_file_system"
  }

  as = concept.managed-file-storage
}

rule "fsx-ontap-file-system" {
  match {
    type = "aws_fsx_ontap_file_system"
  }

  as = concept.managed-file-storage
}


rule "fsx-openzfs-file-system" {
  match {
    type = "aws_fsx_openzfs_file_system"
  }

  as = concept.managed-file-storage
}


rule "fsx-windows-file-system" {
  match {
    type = "aws_fsx_windows_file_system"
  }

  as = concept.managed-file-storage
}
