# Generated by scripts/generate-aws-dialect.ts.
concept "storage-configuration" {
  description = "Configuration contributing to an AWS storage container."
}

rule "s3-directory-bucket" {
  match {
    type = "aws_s3_directory_bucket"
  }

  as = rf.concept.object-storage-container
}
