# Generated by scripts/generate-azure-dialect.ts.
concept "database-component" {
  description = "A table, container, graph, configuration, replica, or policy supporting an Azure database."
}

concept "logical-database" {
  description = "A logical database or keyspace contained by an Azure managed database service."
}
