# Generated by scripts/generate-azure-dialect.ts.
rule "horizondb-cluster" {
  match {
    type  = "azapi_resource"
    where = source.type == "Microsoft.HorizonDb/clusters@2026-01-20-preview"
  }

  as = rf.concept.managed-database
}
