# Generated by scripts/generate-azure-dialect.ts.
concept "messaging-detail" {
  description = "A consumer group, authorization rule, schema, route, or endpoint supporting messaging."
}

concept "messaging-namespace" {
  description = "An Azure messaging namespace owning queues, topics, or event streams."
}

concept "service-bus-topic" {
  description = "An Azure Service Bus topic owning durable subscriptions."
}

concept "event-grid-topic" {
  description = "An Azure Event Grid custom, domain, or system topic owning event subscriptions."
}
