# Generated by scripts/generate-aws-dialect.ts.
concept "cognito-component" {
  description = "Configuration contributing to an Amazon Cognito user pool."
}

concept "cognito-user-pool" {
  description = "Amazon Cognito user pool as a durable AWS architecture scope."
}

rule "cognito-user-pool" {
  match {
    type = "aws_cognito_user_pool"
  }

  as = concept.cognito-user-pool
}
