# Generated by scripts/generate-aws-dialect.ts.
concept "instance-profile" {
  description = "An AWS IAM instance profile associating an IAM role with compute."
}

concept "iam-role" {
  description = "An AWS IAM role, distinct from an explicitly non-human service principal."
}

rule "iam-group" {
  match {
    type = "aws_iam_group"
  }

  as = concept.identity-group
}
