# Generated by scripts/generate-aws-dialect.ts.
concept "load-balancer-component" {
  description = "A listener or target group contributing to an AWS load balancer."
}

rule "alb" {
  match {
    type = "aws_alb"
  }

  as = concept.load-balancer

  identity {
    attributes = ["arn"]
    scope      = "global"
  }

  endpoint {
    attributes = ["arn", "id"]
  }
}
