# Generated by scripts/generate-aws-dialect.ts.
rule "elb" {
  match {
    type = "aws_elb"
  }

  as = concept.load-balancer

  identity {
    attributes = ["arn"]
    scope      = "global"
  }

  endpoint {
    attributes = ["arn", "id"]
  }
}
