# Generated by scripts/generate-aws-dialect.ts.
concept "global-accelerator" {
  description = "An AWS Global Accelerator traffic entry point."
}

concept "global-accelerator-component" {
  description = "A listener or endpoint group contributing to an AWS Global Accelerator."
}
