# Generated by scripts/generate-aws-dialect.ts.
concept "emr-cluster" {
  description = "AWS EMR cluster as a durable AWS architecture entity."
}

concept "emr-cluster-component" {
  description = "Capacity contributing to an Amazon EMR cluster."
}

rule "emr-cluster" {
  match {
    type = "aws_emr_cluster"
  }

  as = concept.emr-cluster
}
