# Generated by scripts/generate-aws-dialect.ts.


concept "event-bus" {
  description = "An Amazon EventBridge event bus."
}

concept "event-component" {
  description = "An Amazon EventBridge rule or target contributing to an event bus."
}
