# Generated by scripts/generate-aws-dialect.ts.
concept "connect-component" {
  description = "Routing or contact configuration contributing to an Amazon Connect instance."
}

concept "connect-instance" {
  description = "Amazon Connect instance as a durable AWS architecture entity."
}

rule "connect-instance" {
  match {
    type = "aws_connect_instance"
  }

  as = concept.connect-instance
}
