# Generated by scripts/generate-aws-dialect.ts.
concept "pinpoint-app" {
  description = "AWS End User Messaging app as a durable AWS architecture entity."
}

concept "pinpoint-component" {
  description = "A channel or event stream contributing to an AWS End User Messaging application."
}

rule "pinpoint-app" {
  match {
    type = "aws_pinpoint_app"
  }

  as = concept.pinpoint-app
}
