#!/usr/bin/env bun

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  type Definition,
  type DialectInventory,
  type Fields,
  officialDialectInventory,
  type Rule,
  type SourceLocation,
} from "./dialects/inventory.ts";

const root = resolve(import.meta.dir, "..");
const generated =
  "<!-- Generated by scripts/generate-provider-coverage.ts from official Dialect sources. -->";
export const symbolAnchor = (id: string) => id.replaceAll(".", "-");
export const ruleAnchor = (name: string) => `rule-${name}`;
const code = (value: string) => `\`${value.replaceAll("|", "\\|").replaceAll("\n", " ")}\``;
const html = (value: string) =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
const sourceUrl = (source: SourceLocation) =>
  `https://github.com/rootform-dev/rootform/blob/dev/dialects/${source.file}#L${source.line}-L${source.endLine}`;
const sourceLink = (source: SourceLocation, label = "Source") => `[${label}](${sourceUrl(source)})`;
const localRuleLink = (id: string, label = id) =>
  `[${code(label)}](#${ruleAnchor(id.split(".rule.")[1]!)})`;
function symbolLink(id: string, label = id): string {
  return id.startsWith("rf.")
    ? `[${code(label)}](../../language/reference/rf-vocabulary.md#${symbolAnchor(id)})`
    : id.includes(".rule.")
      ? localRuleLink(id, label)
      : `[${code(label)}](#${symbolAnchor(id)})`;
}
const header = (title: string, description: string) => [
  "---",
  `title: ${title}`,
  `description: ${JSON.stringify(description)}`,
  "---",
  "",
  generated,
  "",
];
function fieldList(values: Fields): string[] {
  return Object.entries(values).map(([key, value]) => `- ${code(key)}: ${code(value)}`);
}
function definitionView(definition: Definition): string[] {
  const lines = [
    "<div>",
    `<dt id="${symbolAnchor(definition.id)}"><code>${html(definition.id)}</code> <a href="${html(sourceUrl(definition.declarations.find((declaration) => !declaration.inline) ?? definition.declarations[0]!))}">Source</a></dt>`,
  ];
  if (definition.description) lines.push("<dd>", "", definition.description, "", "</dd>");
  lines.push("<dd>", "");
  if (definition.declarations.every((declaration) => declaration.inline))
    lines.push("Introduced by a labeled emission.");
  if (!definition.usedBy.length) lines.push("No Rule in this Dialect uses this definition.");
  else if (definition.usedBy.length <= 3)
    lines.push(
      `Used by ${definition.usedBy.map((id) => localRuleLink(id, id.split(".rule.")[1])).join(", ")}.`,
    );
  else
    lines.push(
      "",
      "<details>",
      `<summary>Used by ${definition.usedBy.length} Rules</summary>`,
      "",
      ...definition.usedBy.map((id) => `- ${localRuleLink(id, id.split(".rule.")[1])}`),
      "",
      "</details>",
    );
  return [...lines, "", "</dd>", "</div>", ""];
}
function ruleView(rule: Rule): string[] {
  const lines = [
    "<details>",
    `<summary><code>${html(rule.id)}</code> <a href="${html(sourceUrl(rule.source))}">Source</a></summary>`,
    "",
    `<div id="${ruleAnchor(rule.name)}"></div>`,
    "",
    `Matches ${code(rule.kind)} instances of ${code(rule.type)}.`,
    "",
    rule.classification
      ? `**Classification:** ${symbolLink(rule.classification)}.`
      : "No classification declared.",
    "",
  ];
  for (const [kind, label] of [
    ["context", "Contexts"],
    ["relation", "Relations"],
    ["contribution", "Contributions"],
  ] as const) {
    const emissions = rule.emissions.filter((emission) => emission.kind === kind);
    if (emissions.length)
      lines.push(
        `**${label}**`,
        "",
        ...emissions.map(
          (emission) =>
            `- ${emission.symbol ? `${symbolLink(emission.symbol)}: ` : ""}targets ${symbolLink(emission.target)} through ${code(emission.via)}.`,
        ),
        "",
      );
  }
  if (rule.members.length) {
    lines.push("**Composition members, in declared order**", "");
    for (const [index, member] of rule.members.entries()) {
      lines.push(
        `${index + 1}. **${code(member.name)}** matches ${code(member.match.type ?? "")} (${code(member.match.kind ?? '"resource"')}), through ${code(member.via)}.${member.dependencies.length ? ` Depends on ${member.dependencies.map(code).join(", ")}.` : ""}`,
      );
      if (member.match.where) lines.push(`   Condition: ${code(member.match.where)}.`);
    }
    lines.push("");
  }
  if (
    rule.condition ||
    Object.keys(rule.identity).length ||
    Object.keys(rule.endpoint).length ||
    rule.emissions.length
  ) {
    lines.push("<details>", "<summary>Conditions, identity and resolution</summary>", "");
    if (rule.condition) lines.push("**Condition**", "", "```rf", rule.condition, "```", "");
    if (Object.keys(rule.identity).length)
      lines.push("**Identity**", "", ...fieldList(rule.identity), "");
    if (Object.keys(rule.endpoint).length)
      lines.push("**Endpoint**", "", ...fieldList(rule.endpoint), "");
    for (const emission of rule.emissions) {
      const values = Object.fromEntries(
        Object.entries(emission.fields).filter(([key]) => !["as", "to", "via"].includes(key)),
      );
      lines.push(
        `**${emission.kind[0]!.toUpperCase()}${emission.kind.slice(1)} through ${code(emission.via)}**`,
        "",
        ...fieldList(values),
        ...fieldList(
          Object.fromEntries(
            Object.entries(emission.match).map(([key, value]) => [`match.${key}`, value]),
          ),
        ),
        "",
      );
    }
    lines.push("</details>", "");
  }
  lines.push("</details>", "");
  return lines;
}

export function dialectCoveragePage(dialect: DialectInventory): string {
  const lines = [
    ...header(
      `${dialect.name} Dialect`,
      dialect.rules.length
        ? "See which types this Dialect interprets and which architectural facts its Rules can establish."
        : "Provider bindings and declared compatibility; no interpretation Rules are declared.",
    ),
    "<details>",
    "<summary>Version and compatibility</summary>",
    "",
    `**Version:** ${code(dialect.version)}.`,
    "",
    "**Provider bindings and declared compatibility**",
    "",
    ...dialect.providers.map(
      (provider) => `- ${code(provider.address)}: ${code(provider.versions)}.`,
    ),
    "",
    "[All official Dialects](../provider-coverage.md)",
    "",
    "</details>",
    "",
  ];
  if (dialect.rules.length) {
    lines.push("## Interpreted types", "");
    const groups = new Map<string, Rule[]>();
    for (const rule of dialect.rules) {
      const key = `${rule.type}/${rule.kind}`;
      groups.set(key, [...(groups.get(key) ?? []), rule]);
    }
    lines.push(
      "Each row identifies a type and instance kind. Conditional Rules retain their individual conditions in the details below.",
      "",
      "| Terraform type | Kind | Classification | Rules |",
      "| --- | --- | --- | --- |",
      ...[...groups.values()].map((rules) => {
        const classifications = [...new Set(rules.map((rule) => rule.classification ?? ""))];
        return `| ${code(rules[0]!.type)} | ${code(rules[0]!.kind)} | ${classifications.map((id) => (id ? symbolLink(id, id.split(".").at(-1)) : "None declared")).join("<br>")} | ${rules.map((rule) => `${localRuleLink(rule.id, rule.name)}${rule.condition ? " (conditional)" : ""}`).join("<br>")} |`;
      }),
      "",
    );
  } else {
    lines.push("## Interpretation", "", "This Dialect declares no interpretation Rules.", "");
    if (dialect.presentation?.hasResources)
      lines.push(
        `Its [presentation mappings](https://github.com/rootform-dev/rootform/blob/dev/dialects/${dialect.presentation.file}) provide visual identities for resource types; they do not classify instances or establish architectural facts.`,
        "",
      );
    else
      lines.push(
        "It records provider bindings and compatibility without adding architectural interpretation.",
        "",
      );
  }
  if (dialect.definitions.length) {
    lines.push("## Local vocabulary", "");
    for (const [kind, title] of [
      ["concept", "Concepts"],
      ["context", "Contexts"],
      ["relation", "Relations"],
    ] as const) {
      const definitions = dialect.definitions.filter((definition) => definition.kind === kind);
      if (definitions.length)
        lines.push(
          `### ${title}`,
          "",
          "<dl>",
          "",
          ...definitions.flatMap(definitionView),
          "</dl>",
          "",
        );
    }
  }
  if (dialect.rfReferences.length)
    lines.push(
      "## RF Vocabulary used",
      "",
      ...dialect.rfReferences.map((id) => `- ${symbolLink(id)}`),
      "",
    );
  if (dialect.rules.length)
    lines.push(
      "## Rule details",
      "",
      "Open a Rule for its declared behavior and source. [Matching](../../language/reference/rules.md#eligibility-pipeline), [emission resolution](../../language/reference/emissions.md) and [composition](../../language/reference/composition.md) define how evidence can establish it.",
      "",
      ...dialect.rules.flatMap(ruleView),
    );
  return lines.join("\n");
}

export function generateProviderCoverage(entries = officialDialectInventory(root)): string {
  return [
    ...header(
      "Provider coverage",
      "Find official Dialects, provider bindings and declared compatibility, then inspect their interpretation coverage.",
    ),
    '<a id="secrets"></a>',
    "This catalog describes **interpretation coverage, not which resources are included in your architecture**. Managed and data instances present in a supported plan or state remain represented in the Form even when no selected Dialect or Rule interprets them. Rootform does not invent a classification, Context or Relation for them.",
    "",
    "Presence in the Form does not imply a permanent card in every Explorer scene. [How Rootform works](../concepts.md#every-observed-instance-starts-with-a-representation) explains the distinction; [Explorer navigation](../guides/explore-architecture.md#reveal-a-secondary-resource) shows how to inspect secondary resources.",
    "",
    "## Official Dialects",
    "",
    '<a id="providers-and-versions"></a>',
    '<a id="interpreted-types-and-declared-facts"></a>',
    "",
    "Find your provider binding, then open its Dialect. A Dialect can bind more than one provider. A binding does not imply complete provider coverage; each constraint describes declared compatibility, not evidence that every provider version was tested. Rootform does not use an observed exact provider version to choose a Rule.",
    "",
    "| Dialect | Version | Provider binding | Declared compatibility |",
    "| --- | :---: | --- | --- |",
    ...entries.flatMap((entry) =>
      entry.providers.map(
        (provider, index) =>
          `| ${index === 0 ? `<a id="${entry.name}"></a>` : ""}[${entry.name}](provider-coverage/${entry.name}.md) | ${code(entry.version)} | ${code(provider.address)} | ${code(provider.versions)} |`,
      ),
    ),
    "",
    "Dialect pages distinguish local vocabulary declarations, RF Vocabulary references and Rule behavior. Declared emissions and composition describe what a Rule can establish; each input must supply the evidence. Resource and data populations, conditions and independent composition members remain distinct. Presentation mappings supply visual identities, not architectural facts.",
    "",
    "## Input limits",
    "",
    "Plan JSON, state JSON and saved Forms are limited to 128 MiB per input. Rootform refuses an oversized input before loading the entire file. The [language limits](../language/reference/diagnostics.md#limits) apply separately to authored and compiled definitions.",
    "",
    "[Choose an input](../inputs/index.md) covers accepted exports. [Plans and saved plans](../inputs/plans.md) covers pairing and reference evidence. [Select Dialects](../cli.md) covers local and OCI selections; this catalog describes the official embedded sources.",
    "",
  ].join("\n");
}

export function generateCoveragePages(
  entries = officialDialectInventory(root),
): Map<string, string> {
  return new Map([
    ["provider-coverage.md", generateProviderCoverage(entries)],
    ...entries.map((entry): [string, string] => [
      `provider-coverage/${entry.name}.md`,
      dialectCoveragePage(entry),
    ]),
  ]);
}
type NavigationItem = {
  label: string;
  page?: string;
  collapsed?: boolean;
  items?: NavigationItem[];
};
export function coverageNavigation(
  nav: NavigationItem[],
  entries: DialectInventory[],
): NavigationItem[] {
  const result = structuredClone(nav);
  const reference = result.find((section) => section.label === "Reference");
  if (!reference?.items) throw new Error("Reference navigation is missing");
  for (const section of result)
    if (section.items)
      section.items = section.items.filter((entry) => entry.label !== "Provider coverage");
  reference.items.unshift({
    label: "Provider coverage",
    collapsed: true,
    items: [
      { label: "Overview", page: "reference/provider-coverage" },
      ...entries.map((entry) => ({
        label: entry.name,
        page: `reference/provider-coverage/${entry.name}`,
      })),
    ],
  });
  return result;
}
if (import.meta.main) {
  const entries = officialDialectInventory(root);
  const pages = generateCoveragePages(entries);
  const navigationPath = join(root, "docs/navigation.json");
  const navigation = JSON.parse(readFileSync(navigationPath, "utf8")) as NavigationItem[];
  const expectedNavigation = coverageNavigation(navigation, entries);
  const directory = join(root, "docs/reference");
  const dialectDirectory = join(directory, "provider-coverage");
  const stale = existsSync(dialectDirectory)
    ? readdirSync(dialectDirectory).filter(
        (file) =>
          file.endsWith(".md") &&
          !pages.has(`provider-coverage/${file}`) &&
          readFileSync(join(dialectDirectory, file), "utf8").includes(generated),
      )
    : [];
  if (process.argv.includes("--check")) {
    if (JSON.stringify(navigation) !== JSON.stringify(expectedNavigation))
      throw new Error("Provider coverage navigation is stale; run bun run generate:coverage");
    for (const [path, content] of pages)
      if (
        !existsSync(join(directory, path)) ||
        readFileSync(join(directory, path), "utf8") !== content
      )
        throw new Error(`Provider coverage is stale: ${path}; run bun run generate:coverage`);
    if (stale.length)
      throw new Error(`Provider coverage has retired generated pages: ${stale.join(", ")}`);
    console.log(`${pages.size} coverage pages match official Dialect sources.`);
  } else {
    const formatted = Bun.spawnSync(
      [join(root, "node_modules/.bin/biome"), "format", "--stdin-file-path=docs/navigation.json"],
      {
        cwd: root,
        stdin: Buffer.from(JSON.stringify(expectedNavigation)),
        stdout: "pipe",
        stderr: "pipe",
      },
    );
    if (formatted.exitCode !== 0) throw new Error(formatted.stderr.toString());
    writeFileSync(navigationPath, formatted.stdout.toString());
    mkdirSync(dialectDirectory, { recursive: true });
    for (const [path, content] of pages) writeFileSync(join(directory, path), content);
    for (const file of stale) rmSync(join(dialectDirectory, file));
  }
}
