#!/usr/bin/env bun

import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { filesBelow, parseRfBlocks } from "./dialects/validate.ts";

type Inventory = { dialects: Array<{ name: string; version: string }> };
const root = resolve(import.meta.dir, "..");

export function ruleCoverage(owner: string, text: string) {
  const type = /\btype\s*=\s*"([^"]+)"/u.exec(text)?.[1];
  if (!type) throw new Error(`${owner}: catalog requires a literal match.type`);
  const match = /\bmatch\s*\{([^}]+)\}/u.exec(text)?.[1] ?? "";
  const kind = /\bkind\s*=\s*"([^"]+)"/u.exec(match)?.[1] ?? "resource";
  const symbols = [
    ...text.matchAll(
      /^\s*as\s*=\s*((?:rf\.)?(?:concept|context|relation|contribution)\.[\w-]+)\s*$/gmu,
    ),
  ]
    .map((entry) => entry[1] ?? "")
    .map((symbol) => (symbol.startsWith("rf.") ? symbol : `${owner}.${symbol}`));
  return { type, kind, symbols: [...new Set(symbols)].sort() };
}

export function generateProviderCoverage(): string {
  const dialectRoot = join(root, "dialects");
  const inventory = JSON.parse(
    readFileSync(join(dialectRoot, "dialects.json"), "utf8"),
  ) as Inventory;
  const entries = inventory.dialects.map(({ name, version }) => {
    const manifest = readFileSync(join(dialectRoot, name, "dialect.rf.hcl"), "utf8");
    const providers = [
      ...manifest.matchAll(/provider\s+"([^"]+)"\s*\{\s*version\s*=\s*"([^"]+)"/gu),
    ].map((match) => ({ address: match[1] ?? "", versions: match[2] ?? "" }));
    if (!providers.length) throw new Error(`${name}: provider bindings missing`);
    const rules = filesBelow(join(dialectRoot, name))
      .filter((file) => file.endsWith(".rf.hcl"))
      .flatMap((file) =>
        parseRfBlocks(readFileSync(join(dialectRoot, file), "utf8"))
          .filter((block) => block.kind === "rule")
          .map((block) => ({ name: block.name, file, ...ruleCoverage(name, block.text) })),
      )
      .sort((a, b) =>
        `${a.type}/${a.kind}/${a.name}`.localeCompare(`${b.type}/${b.kind}/${b.name}`, "en"),
      );
    return { name, version, providers, rules };
  });
  const lines = [
    "---",
    "title: Provider coverage",
    'description: "Find the provider bindings, interpreted resource types and declared architectural facts in the official Dialects before installing Rootform."',
    "---",
    "",
    "<!-- Generated by scripts/generate-provider-coverage.ts from official Dialect sources. -->",
    "",
    "Use this catalog to check whether an official Dialect interprets the resource types in your plan or state. A provider binding does not imply complete provider coverage. A Rule declares architectural Concepts and fact symbols; evidence must still establish each fact, and conditions can limit when the Rule applies.",
    "",
    "## Providers and versions",
    "",
    "Provider addresses bind Rules to their provider. Version constraints declare the Dialect's compatibility envelope; Rootform does not compare them with an observed exact provider version to choose a Rule. Shorthand addresses accept the public Terraform and OpenTofu registry hosts. See [Rules and matching](../../language/reference/rules.md#eligibility-pipeline) for selection and [Limitations](../../limitations.md) for evidence boundaries.",
    "",
    "| Dialect | Version | Provider binding | Declared compatibility |",
    "| --- | :---: | --- | --- |",
    ...entries.flatMap((entry) =>
      entry.providers.map(
        (provider) =>
          `| [${entry.name}](#${entry.name}) | \`${entry.version}\` | \`${provider.address}\` | \`${provider.versions}\` |`,
      ),
    ),
    "",
    "## Interpreted types and declared facts",
    "",
    "Each row comes from an official Rule. `resource` and `data` identify the two populations present in supported exports. Fact symbols describe what the Rule can establish, not a promise that every input produces those facts. Expand a Dialect, find your Terraform type, then open its Rule to inspect conditions, resolution and composition. Types absent here can still have Representations in the Form without interpreted facts.",
    "",
    ...entries.flatMap((entry) => [
      `### ${entry.name}`,
      "",
      "<details>",
      `<summary>${entry.rules.length} Rules</summary>`,
      "",
      "| Terraform type | Kind | Rule and declared symbols |",
      "| --- | --- | --- |",
      ...entry.rules.map(
        (rule) =>
          `| \`${rule.type}\` | \`${rule.kind}\` | [\`${entry.name}.rule.${rule.name}\`](https://github.com/rootform-dev/rootform/blob/dev/dialects/${rule.file})${rule.symbols.length ? `<br>${rule.symbols.map((symbol) => `\`${symbol}\``).join(", ")}` : ""} |`,
      ),
      "",
      "</details>",
      "",
    ]),
    "## Input limits",
    "",
    "Plan JSON, state JSON and saved Forms are limited to 128 MiB per input. Rootform refuses an oversized input before loading the entire file. The [language limits](../../language/reference/diagnostics.md#limits) apply separately to authored and compiled definitions.",
    "",
    "[Choose an input](../../inputs/index.md) explains accepted exports. [Plans and saved plans](../../inputs/plans.md) covers producer format versions, pairing and supported reference evidence. [Select Dialects](../../cli.md) explains local and OCI selections; this catalog describes the official embedded sources.",
    "",
  ];
  // Links resolve from docs/reference, not a provider subdirectory.
  return lines.join("\n").replaceAll("](../../", "](../");
}

if (import.meta.main) {
  const target = join(root, "docs/reference/provider-coverage.md");
  const content = generateProviderCoverage();
  if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf8") !== content)
      throw new Error("Provider coverage is stale; run bun run generate:coverage");
    console.log("Provider coverage matches official Dialect sources.");
  } else writeFileSync(target, content);
}
