# Generated by scripts/generate-aws-dialect.ts.
concept "bedrock-agent-component" {
  description = "Configuration contributing to an Amazon Bedrock agent."
}

concept "bedrockagent-agent" {
  description = "Amazon Bedrock agent as a durable AWS architecture entity."
}



rule "bedrockagent-agent" {
  match {
    type = "aws_bedrockagent_agent"
  }

  as = concept.bedrockagent-agent
}
