# Generated by scripts/generate-aws-dialect.ts.
concept "appsync-api" {
  description = "An AWS AppSync GraphQL API boundary."
}

concept "appsync-component" {
  description = "An AWS AppSync data source, function, or resolver contributing to an API."
}
