// Package schema generates the JSON Schema of the Policy result, format 1,
// from the result types. The Go types remain the source of truth.
package schema

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/rootform-dev/rootform/cli/form"
	"github.com/rootform-dev/rootform/cli/policyresult"
)

// generatedComment is part of the committed schema bytes, which consumers pin
// by digest; the generator stays at the path it names.
const generatedComment = "Generated by `go run ./internal/policy/schema/cmd -write`; DO NOT EDIT."

// Output is the path of the committed schema from the module root.
const Output = "../schemas/policy-result.schema.json"

func stringsOf[T ~string](values ...T) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, string(value))
	}
	return out
}

func vocabularies() map[reflect.Type][]string {
	return map[reflect.Type][]string{
		reflect.TypeOf(policyresult.Status("")):        stringsOf(policyresult.StatusPassed, policyresult.StatusViolated, policyresult.StatusIndeterminate, policyresult.StatusNoDecision, policyresult.StatusFailed),
		reflect.TypeOf(policyresult.Scope("")):         stringsOf(policyresult.ScopeInput, policyresult.ScopeBefore, policyresult.ScopeAfter, policyresult.ScopeBoth),
		reflect.TypeOf(policyresult.Outcome("")):       stringsOf(policyresult.OutcomePassed, policyresult.OutcomeViolated, policyresult.OutcomeIndeterminate),
		reflect.TypeOf(policyresult.PolicyOutcome("")): stringsOf(policyresult.PolicyPassed, policyresult.PolicyViolated, policyresult.PolicyIndeterminate, policyresult.PolicyNoTarget),
		reflect.TypeOf(policyresult.Severity("")):      stringsOf(policyresult.SeverityError, policyresult.SeverityWarning, policyresult.SeverityInfo),
		reflect.TypeOf(form.Stage("")):                 stringsOf(form.Stages()...),
		reflect.TypeOf(form.SemanticOwnerKind("")):     stringsOf(form.OwnerVocabulary, form.OwnerDialect),
	}
}

func fieldOverrides() map[string]map[string]any {
	digest := map[string]any{"type": "string", "pattern": "^sha256:[0-9a-f]{64}$"}
	code := map[string]any{"type": "string", "pattern": "^[A-Z][A-Z0-9_]{1,63}$"}
	return map[string]map[string]any{
		"Result.format_version":          {"const": policyresult.FormatVersion},
		"Result.form_format_version":     {"const": form.FormatVersion},
		"Generator.name":                 {"const": form.GeneratorName},
		"FormIdentity.kind":              {"enum": stringsOf(form.KindState, form.KindPlan, form.KindComparison)},
		"FormIdentity.origin":            {"enum": []string{"saved", "compiled"}},
		"FormIdentity.digest":            digest,
		"Architecture.side":              {"enum": []string{form.SideBefore, form.SideAfter}},
		"Architecture.kind":              {"enum": stringsOf(form.KindState, form.KindPlan)},
		"Architecture.digest":            {"type": "string", "pattern": "^(sha256:[0-9a-f]{64})?$", "description": "Digest of the evaluated input Form; empty only when the architecture could not be read."},
		"ReleaseSet.id":                  {"type": "string", "pattern": "^(release-set:[0-9a-f]{64})?$"},
		"ReleaseSet.manifest_digest":     {"type": "string", "pattern": "^(sha256:[0-9a-f]{64})?$"},
		"ReleaseSetUnit.content_digest":  digest,
		"ReleaseSetUnit.semantic_digest": digest,
		"SemanticOwner.semantic_digest":  digest,
		"SemanticPin.semantic_digest":    digest,
		"SemanticPin.kind":               {"enum": stringsOf(form.OwnerVocabulary, form.OwnerDialect)},
		"PolicyPack.content_digest":      {"type": "string", "pattern": "^(sha256:[0-9a-f]{64})?$"},
		"PolicyPack.linked_digest":       digest,
		"Diagnostic.code":                code,
		"PolicyResult.assertion":         {"type": "string", "description": "The assertion of the evaluated Policy, rendered in canonical expression syntax from the compiled Policy Pack."},
	}
}

type generator struct {
	definitions  map[string]any
	vocabularies map[reflect.Type][]string
	overrides    map[string]map[string]any
	applied      map[string]bool
}

// Generate returns the canonical schema bytes with a trailing newline.
func Generate() ([]byte, error) {
	g := &generator{definitions: map[string]any{}, vocabularies: vocabularies(), overrides: fieldOverrides(), applied: map[string]bool{}}
	root, err := g.object(reflect.TypeOf(policyresult.Result{}))
	if err != nil {
		return nil, err
	}
	for key := range g.overrides {
		if !g.applied[key] {
			return nil, fmt.Errorf("schema override %s names no result field", key)
		}
	}
	root["$schema"] = "https://json-schema.org/draft/2020-12/schema"
	root["$id"] = "https://rootform.dev/schemas/policy-result.schema.json"
	root["$comment"] = generatedComment
	root["title"] = "Policy result, format 1"
	root["description"] = "One rootform check invocation: the Form it received, the scope it evaluated, one Policy selection shared by every architecture, one entry per evaluated architecture and the overall status. The overall status is violated when any architecture is violated, otherwise failed, indeterminate or no_decision when any architecture has no decision, otherwise passed."
	root["$defs"] = g.definitions
	data, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal Policy result schema: %w", err)
	}
	return append(data, '\n'), nil
}

func (g *generator) reference(t reflect.Type) (map[string]any, error) {
	name := t.Name()
	if _, ok := g.definitions[name]; !ok {
		g.definitions[name] = nil
		object, err := g.object(t)
		if err != nil {
			return nil, err
		}
		g.definitions[name] = object
	}
	return map[string]any{"$ref": "#/$defs/" + name}, nil
}

func (g *generator) object(t reflect.Type) (map[string]any, error) {
	properties := map[string]any{}
	required := []string{}
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		if !field.IsExported() {
			continue
		}
		tag := field.Tag.Get("json")
		if tag == "" || tag == "-" {
			return nil, fmt.Errorf("%s.%s has no JSON name", t.Name(), field.Name)
		}
		parts := strings.Split(tag, ",")
		name := parts[0]
		omitempty := false
		for _, option := range parts[1:] {
			omitempty = omitempty || option == "omitempty"
		}
		if override, ok := g.overrides[t.Name()+"."+name]; ok {
			g.applied[t.Name()+"."+name] = true
			properties[name] = override
		} else {
			value, err := g.value(field.Type)
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", t.Name(), field.Name, err)
			}
			properties[name] = value
		}
		if !omitempty {
			required = append(required, name)
		}
	}
	sort.Strings(required)
	return map[string]any{"type": "object", "additionalProperties": false, "properties": properties, "required": required}, nil
}

func (g *generator) value(t reflect.Type) (map[string]any, error) {
	if values, ok := g.vocabularies[t]; ok {
		return map[string]any{"enum": values}, nil
	}
	switch t.Kind() {
	case reflect.Pointer:
		return g.value(t.Elem())
	case reflect.Struct:
		return g.reference(t)
	case reflect.Slice:
		items, err := g.value(t.Elem())
		if err != nil {
			return nil, err
		}
		return map[string]any{"type": "array", "items": items}, nil
	case reflect.String:
		if t.PkgPath() != "" && t.Name() != "string" {
			return nil, fmt.Errorf("named string type %s has no registered vocabulary", t.Name())
		}
		return map[string]any{"type": "string"}, nil
	case reflect.Bool:
		return map[string]any{"type": "boolean"}, nil
	case reflect.Int:
		return map[string]any{"type": "integer", "minimum": 0}, nil
	}
	return nil, fmt.Errorf("unsupported kind %s", t.Kind())
}
