// Package schema generates the JSON Schema of the Form, format 1, from the
// form types. The Go types remain the source of truth.
package schema

import (
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/rootform-dev/rootform/cli/form"
)

// generatedComment is part of the committed schema bytes, which consumers pin
// by digest; the generator stays at the path it names.
const generatedComment = "Generated by `go run ./internal/architecture/document/schema/cmd -write`; DO NOT EDIT."

// Output is the path of the committed schema from the module root.
const Output = "../schemas/form.schema.json"

var (
	inputType      = reflect.TypeOf(form.InputForm{})
	comparisonType = reflect.TypeOf(form.ComparisonForm{})
)

func stringsOf[T ~string](values ...T) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, string(value))
	}
	return out
}

// vocabularies lists every closed vocabulary by its Go type.
func vocabularies() map[reflect.Type][]string {
	return map[reflect.Type][]string{
		reflect.TypeOf(form.Origin("")):               stringsOf(form.OriginPlan, form.OriginState),
		reflect.TypeOf(form.Stage("")):                stringsOf(form.Stages()...),
		reflect.TypeOf(form.ToolIdentity("")):         stringsOf(form.ToolUnestablished, form.ToolTerraform, form.ToolOpenTofu),
		reflect.TypeOf(form.CompletenessValue("")):    stringsOf(form.CompleteTrue, form.CompleteFalse, form.CompleteUnavailable),
		reflect.TypeOf(form.SnapshotStatus("")):       stringsOf(form.SnapshotVerified, form.SnapshotRefused, form.SnapshotAbsent),
		reflect.TypeOf(form.DriftRecords("")):         stringsOf(form.DriftRecordsPresent, form.DriftRecordsAbsent, form.DriftRecordsNotApplicable),
		reflect.TypeOf(form.SemanticOwnerKind("")):    stringsOf(form.OwnerVocabulary, form.OwnerDialect),
		reflect.TypeOf(form.SemanticOrigin("")):       stringsOf(form.SemanticSupplied, form.SemanticLocal, form.SemanticOCI),
		reflect.TypeOf(form.IdentityScope("")):        stringsOf(form.IdentityScopeProvider, form.IdentityScopeGlobal),
		reflect.TypeOf(form.TargetKind("")):           stringsOf(form.TargetConcept, form.TargetRule),
		reflect.TypeOf(form.EmissionKind("")):         stringsOf(form.EmissionContext, form.EmissionContribution, form.EmissionRelation),
		reflect.TypeOf(form.MatchStrategy("")):        stringsOf(form.MatchExact, form.MatchDotAncestor, form.MatchLastSegment),
		reflect.TypeOf(form.NullSemantics("")):        stringsOf(form.NullAbsent, form.NullIndeterminate),
		reflect.TypeOf(form.ExternalPolicy("")):       stringsOf(form.ExternalAllow, form.ExternalDeny),
		reflect.TypeOf(form.Disclosure("")):           stringsOf(form.DiscloseNone, form.DiscloseRecord, form.DiscloseReport),
		reflect.TypeOf(form.DeclarationKind("")):      stringsOf(form.DeclarationResource, form.DeclarationData),
		reflect.TypeOf(form.PopulationStatus("")):     stringsOf(form.PopulationObserved, form.PopulationProvenZero, form.PopulationUnverified),
		reflect.TypeOf(form.AliasAvailability("")):    stringsOf(form.AliasAvailable, form.AliasUnavailable),
		reflect.TypeOf(form.InterpretationStatus("")): stringsOf(form.InterpretationNone, form.InterpretationApplied, form.InterpretationIndeterminate, form.InterpretationFailed),
		reflect.TypeOf(form.RepresentationKind("")):   stringsOf(form.RepresentationManaged, form.RepresentationData, form.RepresentationExternal),
		reflect.TypeOf(form.InstanceStatus("")):       stringsOf(form.StatusPlanned, form.StatusCarried, form.StatusDeferred, form.StatusRecorded, form.StatusExternal),
		reflect.TypeOf(form.IndexKeyKind("")):         stringsOf(form.IndexNone, form.IndexString, form.IndexNumber),
		reflect.TypeOf(form.ImplementationKind("")):   stringsOf(form.ImplementationDirect, form.ImplementationComposition),
		reflect.TypeOf(form.EvidenceKind("")):         stringsOf(form.EvidenceValue, form.EvidenceTraversal, form.EvidenceBoth),
		reflect.TypeOf(form.Outcome("")):              stringsOf(form.OutcomeResolved, form.OutcomeAbsent, form.OutcomeIndeterminate),
		reflect.TypeOf(form.Reason("")):               stringsOf(form.Reasons()...),
		reflect.TypeOf(form.DependencyRole("")):       stringsOf(form.DependencyReference, form.DependencyDependsOn, form.DependencyCount, form.DependencyForEach, form.DependencyProvider),
		reflect.TypeOf(form.ChangeKind("")):           stringsOf(form.ChangeAdded, form.ChangeRemoved, form.ChangeChanged, form.ChangeMoved, form.ChangeReplaced, form.ChangeRecreated),
		reflect.TypeOf(form.FactKind("")):             stringsOf(form.FactContext, form.FactContribution, form.FactRelation),
		reflect.TypeOf(form.DriftConsequence("")):     stringsOf(form.DriftArchitectural, form.DriftNoneUnderDialects, form.DriftIndeterminate, form.DriftUncovered, form.DriftAddressOnly),
		reflect.TypeOf(form.DiagnosticPhase("")): stringsOf(form.PhaseInput, form.PhaseEnrichment, form.PhaseSelection, form.PhaseInterpretation,
			form.PhaseComposition, form.PhaseResolution, form.PhaseComparison, form.PhaseValidation),
		reflect.TypeOf(form.DiagnosticSeverity("")): stringsOf(form.SeverityError, form.SeverityWarning, form.SeverityInfo),
	}
}

// fieldOverrides narrows specific fields beyond their Go type, keyed by
// "<Type>.<json name>".
func fieldOverrides() map[string]map[string]any {
	digest := map[string]any{"type": "string", "pattern": "^sha256:[0-9a-f]{64}$"}
	return map[string]map[string]any{
		"InputForm.format_version":            {"const": form.FormatVersion},
		"ComparisonForm.format_version":       {"const": form.FormatVersion},
		"InputForm.kind":                      {"enum": stringsOf(form.KindState, form.KindPlan)},
		"ComparisonForm.kind":                 {"const": string(form.KindComparison)},
		"Generator.name":                      {"const": form.GeneratorName},
		"Producer.tool_source":                {"const": form.ToolSourceAttested},
		"SnapshotEnrichment.trust":            {"const": form.SnapshotTrustPaired},
		"Scope.refresh_scope":                 {"const": form.RefreshScopeNotExported},
		"Scope.data_sources_covered_by_drift": {"const": false},
		"Scope.deposed_covered_by_drift":      {"const": false},
		"Side.selected_from":                  {"enum": []string{form.SelectedFromInput, form.SelectedFromBefore, form.SelectedFromAfter}},
		"Comparison.name":                     {"enum": []string{form.ComparisonDrift, form.ComparisonChanges, form.ComparisonNet, form.ComparisonCross}},
		"IndeterminateClosure.side":           {"enum": []string{form.SideBefore, form.SideAfter}},
		"IndeterminateClosure.reasons":        {"type": "array", "items": map[string]any{"enum": stringsOf(form.IndeterminateReasons()...)}},
		"RepresentationChange.fields":         {"type": "array", "items": map[string]any{"enum": form.ChangedFields()}},
		"ReleaseSet.id":                       {"type": "string", "pattern": "^release-set:[0-9a-f]{64}$"},
		"ReleaseSet.manifest_digest":          digest,
		"ReleaseSetUnit.content_digest":       digest,
		"ReleaseSetUnit.semantic_digest":      digest,
		"SemanticOwner.content_digest":        digest,
		"SemanticOwner.semantic_digest":       digest,
		"OwnerReplacement.digest":             digest,
		"Emission.id":                         {"type": "string", "pattern": "^emission:[0-9a-f]{64}$"},
		"Diagnostic.id":                       {"type": "string", "pattern": "^diagnostic:[0-9a-f]{64}$"},
		"Diagnostic.code":                     {"type": "string", "pattern": "^[A-Z][A-Z0-9_]{1,63}$"},
		"ComparisonProblem.code":              {"type": "string", "pattern": "^[A-Z][A-Z0-9_]{1,63}$"},
		"Representation.actions":              {"type": "array", "items": map[string]any{"enum": actions()}},
		"DriftEntry.actions":                  {"type": "array", "minItems": 1, "items": map[string]any{"enum": actions()}},
		"Representation.identity": {
			"type": "object", "additionalProperties": map[string]any{"type": "string"},
			"description": "External endpoints only, under the record or report disclosure tier.",
		},
	}
}

func actions() []string { return []string{"no-op", "create", "read", "update", "delete", "forget"} }

type generator struct {
	definitions  map[string]any
	vocabularies map[reflect.Type][]string
	overrides    map[string]map[string]any
	applied      map[string]bool
}

// Generate returns the canonical schema bytes with a trailing newline.
func Generate() ([]byte, error) {
	g := &generator{definitions: map[string]any{}, vocabularies: vocabularies(), overrides: fieldOverrides(), applied: map[string]bool{}}
	for _, root := range []reflect.Type{inputType, comparisonType} {
		if _, err := g.reference(root); err != nil {
			return nil, err
		}
	}
	// An override naming no field would silently leave that field on its
	// generic Go shape, so a misspelt key fails generation.
	for key := range g.overrides {
		if !g.applied[key] {
			return nil, fmt.Errorf("schema override %s names no document field", key)
		}
	}
	root := map[string]any{
		"$schema":  "https://json-schema.org/draft/2020-12/schema",
		"$id":      "https://rootform.dev/schemas/form.schema.json",
		"$comment": generatedComment,
		"title":    "Form, format 1",
		"oneOf": []any{
			map[string]any{"$ref": "#/$defs/InputForm"},
			map[string]any{"$ref": "#/$defs/ComparisonForm"},
		},
		"$defs": g.definitions,
	}
	data, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal Form schema: %w", err)
	}
	return append(data, '\n'), nil
}

func (g *generator) reference(t reflect.Type) (map[string]any, error) {
	name := t.Name()
	if _, ok := g.definitions[name]; !ok {
		g.definitions[name] = nil
		object, err := g.object(t)
		if err != nil {
			return nil, err
		}
		g.definitions[name] = object
	}
	return map[string]any{"$ref": "#/$defs/" + name}, nil
}

func (g *generator) object(t reflect.Type) (map[string]any, error) {
	properties := map[string]any{}
	required := []string{}
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		if !field.IsExported() {
			continue
		}
		tag := field.Tag.Get("json")
		if tag == "" || tag == "-" {
			return nil, fmt.Errorf("%s.%s has no JSON name", t.Name(), field.Name)
		}
		parts := strings.Split(tag, ",")
		name := parts[0]
		omitempty := false
		for _, option := range parts[1:] {
			if option == "omitempty" {
				omitempty = true
			}
		}
		if override, ok := g.overrides[t.Name()+"."+name]; ok {
			g.applied[t.Name()+"."+name] = true
			properties[name] = override
		} else {
			value, err := g.value(field.Type)
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", t.Name(), field.Name, err)
			}
			properties[name] = value
		}
		if !omitempty {
			required = append(required, name)
		}
	}
	sort.Strings(required)
	return map[string]any{
		"type": "object", "additionalProperties": false,
		"properties": properties, "required": required,
	}, nil
}

func (g *generator) value(t reflect.Type) (map[string]any, error) {
	if values, ok := g.vocabularies[t]; ok {
		return map[string]any{"enum": values}, nil
	}
	switch t.Kind() {
	case reflect.Pointer:
		return g.value(t.Elem())
	case reflect.Struct:
		return g.reference(t)
	case reflect.Slice:
		items, err := g.value(t.Elem())
		if err != nil {
			return nil, err
		}
		return map[string]any{"type": "array", "items": items}, nil
	case reflect.Map:
		values, err := g.value(t.Elem())
		if err != nil {
			return nil, err
		}
		out := map[string]any{"type": "object", "additionalProperties": values}
		if keys, ok := g.vocabularies[t.Key()]; ok {
			out["propertyNames"] = map[string]any{"enum": keys}
		}
		return out, nil
	case reflect.String:
		if t.PkgPath() != "" && t.Name() != "string" {
			return nil, fmt.Errorf("named string type %s has no registered vocabulary", t.Name())
		}
		return map[string]any{"type": "string"}, nil
	case reflect.Bool:
		return map[string]any{"type": "boolean"}, nil
	case reflect.Int:
		return map[string]any{"type": "integer", "minimum": 0}, nil
	}
	return nil, fmt.Errorf("unsupported kind %s", t.Kind())
}
